### ISSUE TITLE
Check for full alias name

### ISSUE THREAD

**Issue by trimailov** [ProgrammersOfVilnius/gtimelog2jira#6]
```
$ cat ~/.gtimelog/gtimelogrc

<...>
[gtimelog2jira:aliases]
# meetings and discussions
MEET = SSPACE-192
# meetings and discussions
SPLAT-MEET = SPLAT-9  # should be MEET-SPLAT, SPLAT-MEET works, whereas MEET-SPLAT does not.
```

When uploading timesheets to jira, entries marked with `SPLAT-MEET` will be uploaded to ticket SSPACE-192 (marked as `MEET`).

Would be great that `gtimelog2jira` could be able to find distinct issue aliases.

**Comment by mgedmin** [comment]
I was unable to reproduce the bug in the test suite.  Here's what I tried:

```python
def test_parse_timelog_alias_clash():
    entries = [
        gtimelog2jira.Entry(datetime.datetime(2014, 3, 31, 14, 48),
                            datetime.datetime(2014, 3, 31, 17, 10),
                            'project2: meeting about something (SPLAT-MEET)'),
    ]
    projects = ['SSPACE', 'SPLAT']
    aliases = {
        'MEET': 'SSPACE-192',
        'SPLAT-MEET': 'SPLAT-9',
    }
    assert list(gtimelog2jira.parse_timelog(entries, projects, aliases)) == [
        gtimelog2jira.WorkLog(entries[0], 'SPLAT-9', 'meeting about something'),
    ]
```

**Comment by mgedmin** [comment]
The code constructs a regex that matches all known aliases and projects (the latter followed by a hyphen and some digits).  The leftmost match always wins.  When two matches are possible at the same position, the longest match wins.

I don't see how MEET could win over SPLAT-MEET, unless there was another MEET before it on the same line?

**Comment by trimailov** [comment]
I've remembered that I've "hacked" my config to make this work.

Take a note on aliases in this changed test:

```python
def test_parse_timelog_alias_clash():
    entries = [
        gtimelog2jira.Entry(datetime.datetime(2014, 3, 31, 14, 48),
                            datetime.datetime(2014, 3, 31, 17, 10),
                            'project2: meeting about something (MEET-SPLAT)'),
    ]
    projects = ['SSPACE', 'SPLAT']
    aliases = {
        'MEET': 'SSPACE-192',
        'MEET-SPLAT': 'SPLAT-9',
    }
    print(list(gtimelog2jira.parse_timelog(entries, projects, aliases)))
    # <WorkLog: SSPACE-192, meeting about something (MEET-SPLAT)>]
    print(gtimelog2jira.WorkLog(entries[0], 'SPLAT-9', 'meeting about something'))
    # <WorkLog: SPLAT-9, meeting about something>

    assert list(gtimelog2jira.parse_timelog(entries, projects, aliases)) == [
        gtimelog2jira.WorkLog(entries[0], 'SPLAT-9', 'meeting about something'),
    ]
```

Also why this test does not fail? If WorkLogs are not the same?

```
> /Users/justas/work/pov/gtimelog2jira/tests.py(395)test_parse_timelog_alias_clash()
-> assert list(gtimelog2jira.parse_timelog(entries, projects, aliases)) == [
(Pdb) wl1 = list(gtimelog2jira.parse_timelog(entries, projects, aliases))[0]
(Pdb) wl2 = gtimelog2jira.WorkLog(entries[0], 'SPLAT-9', 'meeting about something')
(Pdb) id(wl1)
4356733472
(Pdb) id(wl2)
4356732632
(Pdb) wl1
<WorkLog: SSPACE-192, meeting about something (MEET-SPLAT)>
(Pdb) wl2
<WorkLog: SPLAT-9, meeting about something>
(Pdb) wl1.__dict__
{'entry': Entry(start=datetime.datetime(2014, 3, 31, 14, 48), end=datetime.datetime(2014, 3, 31, 17, 10), message='project2: meeting about something (MEET-SPLAT)'), 'start': datetime.datetime(2014, 3, 31, 14, 48), 'end': datetime.datetime(2014, 3, 31, 17, 10), 'seconds': 8520, 'issue': 'SSPACE-192', 'comment': 'meeting about something (MEET-SPLAT)'}
(Pdb) wl2.__dict__
{'entry': Entry(start=datetime.datetime(2014, 3, 31, 14, 48), end=datetime.datetime(2014, 3, 31, 17, 10), message='project2: meeting about something (MEET-SPLAT)'), 'start': datetime.datetime(2014, 3, 31, 14, 48), 'end': datetime.datetime(2014, 3, 31, 17, 10), 'seconds': 8520, 'issue': 'SPLAT-9', 'comment': 'meeting about something'}
(Pdb) wl1 == wl2
True
```

**Comment by trimailov** [comment]
> Also why this test does not fail? If WorkLogs are not the same?

Well of course: 
https://github.com/ProgrammersOfVilnius/gtimelog2jira/blob/master/gtimelog2jira.py#L44-L47 :)

**Comment by trimailov** [comment]
@mgedmin  should I label this as `bug` or `enhancement`? Or should we ignore this as `wontfix`?

**Comment by mgedmin** [comment]
> Well of course:
https://github.com/ProgrammersOfVilnius/gtimelog2jira/blob/master/gtimelog2jira.py#L44-L47 :)

Oh my this is *terrible*.  Why.

> @mgedmin should I label this as bug or enhancement? Or should we ignore this as wontfix?

It's a bug IMHO.

**Comment by mgedmin** [comment]
So, I've fixed the `__eq__` in  a729c96, but I still cannot reproduce the bug.

My test was failing because I misremembered the exact rule of stripping the issue from the comment field.  The associated issue field is assigned correctly, on my machine.

<details>

```
================================================================= FAILURES =================================================================
____________________________________________________________ test_parse_timelog ____________________________________________________________
Traceback (most recent call last):
  File "/home/mg/src/gtimelog2jira/tests.py", line 33, in test_parse_timelog
    assert list(gtimelog2jira.parse_timelog(entries, ['ABC'], aliases)) == [
AssertionError: assert [<WorkLog: AB...p (ABC-MISC)>] == [<WorkLog: ABC...p (ABC-MISC)>]
  At index 0 diff: <WorkLog: ABC-1, some work> != <WorkLog: ABC-1, ABC-1 some work>
  Full diff:
  - [<WorkLog: ABC-1, some work>, <WorkLog: ABC-42, meeting prep (ABC-MISC)>]
  + [<WorkLog: ABC-1, ABC-1 some work>, <WorkLog: ABC-42, meeting prep (ABC-MISC)>]
  ?                   ++++++
______________________________________________________ test_parse_timelog_alias_clash ______________________________________________________
Traceback (most recent call last):
  File "/home/mg/src/gtimelog2jira/tests.py", line 50, in test_parse_timelog_alias_clash
    assert list(gtimelog2jira.parse_timelog(entries, projects, aliases)) == [
AssertionError: assert [<WorkLog: SP...(SPLAT-MEET)>] == [<WorkLog: SPL...ut something>]
  At index 0 diff: <WorkLog: SPLAT-9, meeting about something (SPLAT-MEET)> != <WorkLog: SPLAT-9, meeting about something>
  Full diff:
  - [<WorkLog: SPLAT-9, meeting about something (SPLAT-MEET)>]
  ?                                            -------------
  + [<WorkLog: SPLAT-9, meeting about something>]
```

</details>

Can you tell me what Python version you use?

**Comment by trimailov** [comment]
https://github.com/ProgrammersOfVilnius/gtimelog2jira/pull/7/files#diff-f4bc68ff01eef7bed2f3a64cad7d37caR388

It works with `SPLAT-MEET`, though it does not with `MEET-SPLAT`. 

My original issue description is incorrect regarding this. Sorry for the mix-up.

**Comment by mgedmin** [comment]
Ah!  Thank you.

Looks like my assumption that regexes always return the longest match was incorrect!
